FROM python:3.11-slim

WORKDIR /app

COPY requirements-streamlit.txt .

RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY streamlit ./streamlit

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.address=0.0.0.0", "--server.port=8501"]